<?php

/*
 * Declare the namespace matching Laravel's directory structure
 * for feature tests to ensure correct autoloading via Composer.
 */
namespace Tests\Feature;

/*
 * Import the RefreshDatabase trait to reset the database state
 * after each test execution to prevent cross-test contamination.
 */
use Illuminate\Foundation\Testing\RefreshDatabase;

/*
 * Import the MpesaC2bTransaction Eloquent model to verify
 * database record persistence during test assertions.
 */
use App\Models\MpesaC2bTransaction;

/*
 * Import the base TestCase class provided by Laravel framework
 * which sets up the application environment for HTTP testing.
 */
use Tests\TestCase;

/*
 * Define the feature test class extending the core TestCase
 * to test M-Pesa C2B API functionality end-to-end.
 */
class MpesaC2bTest extends TestCase
{
    /*
     * Include the RefreshDatabase trait inside the test class
     * to automatically execute migrations before running tests.
     */
    use RefreshDatabase;

    /*
     * Define a test method to verify successful processing
     * of a valid M-Pesa C2B callback payload request.
     */
    public function test_mpesa_c2b_callback_saves_data_and_returns_success_response(): void
    {
        /*
         * Define a mock JSON payload matching Safaricom's exact
         * structure and fields sent during a C2B transaction.
         */
        $payload = [
            /*
             * Specify transaction type such as Pay Bill or
             * Customer Buy Goods depending on the shortcode setup.
             */
            'TransactionType' => 'Pay Bill',

            /*
             * Provide a unique M-Pesa transaction reference ID
             * generated by Safaricom for testing uniqueness.
             */
            'TransID' => 'RKT9876543',

            /*
             * Provide the transaction timestamp in Safaricom's
             * standard YYYYMMDDHHMMSS date string format.
             */
            'TransTime' => '20260810120000',

            /*
             * Provide the transaction amount as a numeric string
             * representing Kenya Shillings paid by customer.
             */
            'TransAmount' => '2500.00',

            /*
             * Provide the receiver business shortcode (Paybill number)
             * registered on Safaricom's Daraja portal.
             */
            'BusinessShortCode' => '600000',

            /*
             * Provide the customer's account reference number
             * entered during payment on the M-Pesa menu.
             */
            'BillRefNumber' => 'INV-2026-001',

            /*
             * Provide an optional invoice number field which can be
             * empty or contain partner invoice details.
             */
            'InvoiceNumber' => '',

            /*
             * Provide the updated utility account organization balance
             * string after deducting or adding the funds.
             */
            'OrgAccountBalance' => '150000.00',

            /*
             * Provide an optional third-party transaction reference
             * ID used when integrating external aggregators.
             */
            'ThirdPartyTransID' => '',

            /*
             * Provide the paying customer phone number formatted with
             * country code 254 without leading plus sign.
             */
            'MSISDN' => '254712345678',

            /*
             * Provide the customer's first name as registered on
             * their Safaricom M-Pesa mobile account.
             */
            'FirstName' => 'Jane',

            /*
             * Provide the customer's middle name as registered on
             * their Safaricom M-Pesa mobile account.
             */
            'MiddleName' => 'W',

            /*
             * Provide the customer's last name as registered on
             * their Safaricom M-Pesa mobile account.
             */
            'LastName' => 'Doe',
        ];

        /*
         * Execute a POST HTTP request to the designated API endpoint
         * passing the constructed array payload as a JSON body.
         */
        $response = $this->postJson('/api/mpesa/c2b/confirmation', $payload);

        /*
         * Assert that the API endpoint returns an HTTP 200 OK
         * status code confirming receipt to Safaricom servers.
         */
        $response->assertStatus(200);

        /*
         * Assert that the returned JSON body matches Safaricom's
         * required ResultCode and ResultDesc response structure.
         */
        $response->assertExactJson([
            /*
             * Assert that ResultCode is integer zero representing
             * successful acceptance of the transaction data.
             */
            'ResultCode' => 0,

            /*
             * Assert that ResultDesc contains the exact confirmation
             * string message expected by the API interface.
             */
            'ResultDesc' => 'Confirmation received successfully',
        ]);

        /*
         * Assert that the record exists inside the database table
         * with all values properly mapped and cast to strings.
         */
        $this->assertDatabaseHas('mpesa_c2b_transactions', [
            /*
             * Check that the transaction_type column matches input.
             */
            'transaction_type' => 'Pay Bill',

            /*
             * Check that the trans_id column matches the unique ID.
             */
            'trans_id' => 'RKT9876543',

            /*
             * Check that the trans_time column matches formatted time.
             */
            'trans_time' => '20260810120000',

            /*
             * Check that the trans_amount column matches amount string.
             */
            'trans_amount' => '2500.00',

            /*
             * Check that the business_short_code matches shortcode.
             */
            'business_short_code' => '600000',

            /*
             * Check that the bill_ref_number matches reference.
             */
            'bill_ref_number' => 'INV-2026-001',

            /*
             * Check that the msisdn column matches customer phone.
             */
            'msisdn' => '254712345678',

            /*
             * Check that the first_name column matches customer name.
             */
            'first_name' => 'Jane',

            /*
             * Check that the middle_name column matches middle initial.
             */
            'middle_name' => 'W',

            /*
             * Check that the last_name column matches family name.
             */
            'last_name' => 'Doe',
        ]);
    }

    /*
     * Define a test method to verify duplicate transaction requests
     * update existing database records instead of throwing errors.
     */
    public function test_mpesa_c2b_callback_handles_duplicate_transactions(): void
    {
        /*
         * Define a mock JSON payload containing a duplicate TransID.
         */
        $payload = [
            'TransactionType' => 'Pay Bill',
            'TransID' => 'RKT9876543',
            'TransTime' => '20260810120000',
            'TransAmount' => '2500.00',
            'BusinessShortCode' => '600000',
            'BillRefNumber' => 'INV-2026-001',
            'InvoiceNumber' => '',
            'OrgAccountBalance' => '150000.00',
            'ThirdPartyTransID' => '',
            'MSISDN' => '254712345678',
            'FirstName' => 'Jane',
            'MiddleName' => 'W',
            'LastName' => 'Doe',
        ];

        /*
         * Send the first POST request to seed the initial record.
         */
        $this->postJson('/api/mpesa/c2b/confirmation', $payload);

        /*
         * Send the second POST request with identical payload data.
         */
        $secondResponse = $this->postJson('/api/mpesa/c2b/confirmation', $payload);

        /*
         * Assert HTTP status remains 200 on duplicate callbacks.
         */
        $secondResponse->assertStatus(200);

        /*
         * Assert database contains exactly one record with this TransID.
         */
        $this->assertEquals(1, MpesaC2bTransaction::where('trans_id', 'RKT9876543')->count());
    }
}